services:
  db:
    image: mariadb:10.11
    container_name: dcim-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dcim_root_2024
      MYSQL_DATABASE: dcim
      MYSQL_USER: dcim
      MYSQL_PASSWORD: dcim_pass_2024
    volumes:
      - dcim-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  opendcim:
    build:
      context: ./opendcim
      args:
        OPENDCIM_VERSION: "23.04"
    container_name: dcim-web
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - dcim-html:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/install.php || true"]
      interval: 15s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: dcim-pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: dcim_root_2024
    ports:
      - "8081:80"

volumes:
  dcim-db:
  dcim-html: